spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ub?useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useSSL=false&sessionVariables=sql_mode=''&useUnicode=true&characterEncoding=utf8   
    username: root 
    password: password
  
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/pareto?currentSchema=norpac
#    username: norpac 
#    password: password
    
cognito:
  region: us-west-2 
  pool-id: us-west-2_O5NAjDcDT

