spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/norpac?currentSchema=public
    username: norpac 
    password: password

tenant: 
  name: norpac
