spring:
  application:
    name: pareto-factory

  jpa:
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        multiTenancy: DATABASE
    
server:
  port: ${PORT:8086}

management:
  endpoints:
    web:
      exposure:
        include: "*"

pareto-factory:
  version: '@project.version@'
  tenant: norpac