services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: norpac
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fake.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8085:80"
    depends_on:
      - postgres

  postgrest:
    image: postgrest/postgrest
    container_name: postgrest
    restart: always
    environment:
      PGRST_DB_URI: postgres://admin:password@postgres:5432/norpac
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: web_anon
    ports:
      - "8086:3000"
    depends_on:
      - postgres

volumes:
  postgres_data: